class AppStrings {
  AppStrings(this.languageCode);

  final String languageCode;

  static const supportedLanguages = <String, String>{
    'en-US': 'English',
    'bn-BD': 'বাংলা (Bangla)',
    'ru-RU': 'Русский (Russian)',
    'hi-IN': 'हिन्दी (Hindi)',
  };

  static const _values = <String, Map<String, String>>{
    'en-US': {
      'appName': 'WVAB',
      'appSubtitle': 'Wireless Vision Aid\nfor the Blind',
      'startAssistance': 'START\nASSISTANCE',
      'settings': 'Settings',
      'history': 'History',
      'notConnected': 'Not Connected',
      'assistance': 'Assistance',
      'cameraStarting': 'Starting camera…',
      'cameraUnavailable': 'Camera unavailable',
      'inferencePending': 'Secure detection is not active in this build.',
      'mode': 'Mode',
      'edgeServer': 'Edge Server',
      'onDevice': 'On-device',
      'speed': 'Speed',
      'normal': 'Normal',
      'pause': 'Pause',
      'resume': 'Resume',
      'stop': 'Stop',
      'torch': 'Torch',
      'general': 'General',
      'detection': 'Detection',
      'audio': 'Audio',
      'about': 'About',
      'serverConnection': 'Server Connection',
      'serverIp': 'Server IP',
      'port': 'Port',
      'feedback': 'Audio & Feedback',
      'language': 'Language / ভাষা',
      'speechRate': 'Speech Rate',
      'vibration': 'Vibration',
      'hapticIntensity': 'Haptic Intensity',
      'medium': 'Medium',
      'saveChanges': 'Save Changes',
      'languageTitle': 'Language',
      'languageHint': 'This changes the app interface and voice-guidance language.',
      'connection': 'Connection',
      'endpointConfigured': 'Endpoint configured',
      'transportPending': 'Secure UDP Protocol v2 mobile transport is not connected yet.',
      'connectionHealth': 'Connection Health',
      'packetsSent': 'Packets Sent',
      'packetsReceived': 'Packets Received',
      'packetLoss': 'Packet Loss',
      'lastUpdate': 'Last Update',
      'reconnection': 'Reconnection',
      'autoReconnect': 'Auto Reconnect',
      'reconnectInterval': 'Reconnect Interval',
      'seconds5': '5 sec',
      'testConnection': 'Test Connection',
      'endpointValid': 'Endpoint format is valid. Secure transport is still pending.',
      'detectionSettings': 'Detection Settings',
      'confidenceThreshold': 'Confidence Threshold',
      'detectClasses': 'Detect Classes',
      'person': 'Person',
      'vehicle': 'Vehicle',
      'bicycle': 'Bicycle',
      'motorcycle': 'Motorcycle',
      'obstacle': 'Obstacle',
      'stairs': 'Stairs',
      'curb': 'Curb',
      'historyEmpty': 'No detection history recorded yet.',
      'historyHint': 'Events will appear here after the detection pipeline is integrated.',
      'today': 'Today',
      'privacyPolicy': 'Privacy Policy',
      'openSourceLicenses': 'Open Source Licenses',
      'howItWorks': 'How It Works',
      'contact': 'Contact',
      'version': 'v1.0.0 mobile demo',
      'madeForAccessibility': 'Built for accessibility',
      'prototypeNotice': 'Assistive prototype — not a certified navigation or safety device.',
      'flashUnavailable': 'Torch is unavailable on this camera.',
      'restartCamera': 'Restart camera',
      'voiceGuidance': 'Voice guidance',
    },
    'bn-BD': {
      'appName': 'WVAB',
      'appSubtitle': 'দৃষ্টিপ্রতিবন্ধীদের জন্য\nওয়্যারলেস ভিশন সহায়তা',
      'startAssistance': 'সহায়তা\nশুরু করুন',
      'settings': 'সেটিংস',
      'history': 'ইতিহাস',
      'notConnected': 'সংযুক্ত নয়',
      'assistance': 'সহায়তা',
      'cameraStarting': 'ক্যামেরা চালু হচ্ছে…',
      'cameraUnavailable': 'ক্যামেরা পাওয়া যায়নি',
      'inferencePending': 'এই বিল্ডে নিরাপদ ডিটেকশন এখনো সক্রিয় নয়।',
      'mode': 'মোড',
      'edgeServer': 'এজ সার্ভার',
      'onDevice': 'ডিভাইসে',
      'speed': 'গতি',
      'normal': 'স্বাভাবিক',
      'pause': 'বিরতি',
      'resume': 'চালু করুন',
      'stop': 'বন্ধ',
      'torch': 'টর্চ',
      'general': 'সাধারণ',
      'detection': 'ডিটেকশন',
      'audio': 'অডিও',
      'about': 'সম্পর্কে',
      'serverConnection': 'সার্ভার সংযোগ',
      'serverIp': 'সার্ভার IP',
      'port': 'পোর্ট',
      'feedback': 'অডিও ও ফিডব্যাক',
      'language': 'ভাষা',
      'speechRate': 'কথার গতি',
      'vibration': 'ভাইব্রেশন',
      'hapticIntensity': 'হ্যাপটিক তীব্রতা',
      'medium': 'মাঝারি',
      'saveChanges': 'পরিবর্তন সংরক্ষণ',
      'languageTitle': 'ভাষা',
      'languageHint': 'এটি অ্যাপের ইন্টারফেস ও ভয়েস-গাইডেন্সের ভাষা পরিবর্তন করবে।',
      'connection': 'সংযোগ',
      'endpointConfigured': 'এন্ডপয়েন্ট কনফিগার করা আছে',
      'transportPending': 'Secure UDP Protocol v2 মোবাইল ট্রান্সপোর্ট এখনো সংযুক্ত নয়।',
      'connectionHealth': 'সংযোগের অবস্থা',
      'packetsSent': 'প্যাকেট পাঠানো',
      'packetsReceived': 'প্যাকেট পাওয়া',
      'packetLoss': 'প্যাকেট লস',
      'lastUpdate': 'সর্বশেষ আপডেট',
      'reconnection': 'পুনঃসংযোগ',
      'autoReconnect': 'স্বয়ংক্রিয় পুনঃসংযোগ',
      'reconnectInterval': 'পুনঃসংযোগ বিরতি',
      'seconds5': '৫ সেকেন্ড',
      'testConnection': 'সংযোগ পরীক্ষা',
      'endpointValid': 'এন্ডপয়েন্ট ফরম্যাট সঠিক। নিরাপদ ট্রান্সপোর্ট এখনো বাকি।',
      'detectionSettings': 'ডিটেকশন সেটিংস',
      'confidenceThreshold': 'কনফিডেন্স থ্রেশহোল্ড',
      'detectClasses': 'ডিটেক্ট ক্লাস',
      'person': 'মানুষ',
      'vehicle': 'যানবাহন',
      'bicycle': 'সাইকেল',
      'motorcycle': 'মোটরসাইকেল',
      'obstacle': 'বাধা',
      'stairs': 'সিঁড়ি',
      'curb': 'কার্ব',
      'historyEmpty': 'এখনো কোনো ডিটেকশন ইতিহাস রেকর্ড হয়নি।',
      'historyHint': 'ডিটেকশন পাইপলাইন যুক্ত হলে ইভেন্ট এখানে দেখা যাবে।',
      'today': 'আজ',
      'privacyPolicy': 'গোপনীয়তা নীতি',
      'openSourceLicenses': 'ওপেন সোর্স লাইসেন্স',
      'howItWorks': 'কীভাবে কাজ করে',
      'contact': 'যোগাযোগ',
      'version': 'v1.0.0 মোবাইল ডেমো',
      'madeForAccessibility': 'অ্যাক্সেসিবিলিটির জন্য তৈরি',
      'prototypeNotice': 'সহায়ক প্রোটোটাইপ — সার্টিফায়েড ন্যাভিগেশন বা সেফটি ডিভাইস নয়।',
      'flashUnavailable': 'এই ক্যামেরায় টর্চ পাওয়া যায় না।',
      'restartCamera': 'ক্যামেরা পুনরায় চালু করুন',
      'voiceGuidance': 'ভয়েস গাইডেন্স',
    },
    'ru-RU': {
      'appName': 'WVAB',
      'appSubtitle': 'Беспроводная визуальная помощь\nдля незрячих',
      'startAssistance': 'НАЧАТЬ\nПОМОЩЬ',
      'settings': 'Настройки',
      'history': 'История',
      'notConnected': 'Нет подключения',
      'assistance': 'Помощь',
      'cameraStarting': 'Запуск камеры…',
      'cameraUnavailable': 'Камера недоступна',
      'inferencePending': 'Защищённое распознавание в этой сборке ещё не активно.',
      'mode': 'Режим',
      'edgeServer': 'Edge-сервер',
      'onDevice': 'На устройстве',
      'speed': 'Скорость',
      'normal': 'Обычная',
      'pause': 'Пауза',
      'resume': 'Продолжить',
      'stop': 'Стоп',
      'torch': 'Фонарик',
      'general': 'Основное',
      'detection': 'Обнаружение',
      'audio': 'Аудио',
      'about': 'О приложении',
      'serverConnection': 'Подключение к серверу',
      'serverIp': 'IP сервера',
      'port': 'Порт',
      'feedback': 'Аудио и обратная связь',
      'language': 'Язык',
      'speechRate': 'Скорость речи',
      'vibration': 'Вибрация',
      'hapticIntensity': 'Интенсивность вибрации',
      'medium': 'Средняя',
      'saveChanges': 'Сохранить изменения',
      'languageTitle': 'Язык',
      'languageHint': 'Меняет язык интерфейса и голосовых подсказок.',
      'connection': 'Подключение',
      'endpointConfigured': 'Адрес сервера настроен',
      'transportPending': 'Мобильный Secure UDP Protocol v2 пока не подключён.',
      'connectionHealth': 'Состояние подключения',
      'packetsSent': 'Отправлено пакетов',
      'packetsReceived': 'Получено пакетов',
      'packetLoss': 'Потери пакетов',
      'lastUpdate': 'Последнее обновление',
      'reconnection': 'Переподключение',
      'autoReconnect': 'Автоподключение',
      'reconnectInterval': 'Интервал',
      'seconds5': '5 сек',
      'testConnection': 'Проверить подключение',
      'endpointValid': 'Формат адреса корректен. Защищённый транспорт ещё не подключён.',
      'detectionSettings': 'Настройки обнаружения',
      'confidenceThreshold': 'Порог уверенности',
      'detectClasses': 'Классы объектов',
      'person': 'Человек',
      'vehicle': 'Транспорт',
      'bicycle': 'Велосипед',
      'motorcycle': 'Мотоцикл',
      'obstacle': 'Препятствие',
      'stairs': 'Лестница',
      'curb': 'Бордюр',
      'historyEmpty': 'История обнаружений пока пуста.',
      'historyHint': 'События появятся после интеграции конвейера распознавания.',
      'today': 'Сегодня',
      'privacyPolicy': 'Политика конфиденциальности',
      'openSourceLicenses': 'Лицензии Open Source',
      'howItWorks': 'Как это работает',
      'contact': 'Контакты',
      'version': 'v1.0.0 мобильное демо',
      'madeForAccessibility': 'Создано для доступности',
      'prototypeNotice': 'Вспомогательный прототип — не сертифицированное навигационное устройство.',
      'flashUnavailable': 'Фонарик недоступен на этой камере.',
      'restartCamera': 'Перезапустить камеру',
      'voiceGuidance': 'Голосовые подсказки',
    },
    'hi-IN': {
      'appName': 'WVAB',
      'appSubtitle': 'दृष्टिबाधित लोगों के लिए\nवायरलेस विज़न सहायता',
      'startAssistance': 'सहायता\nशुरू करें',
      'settings': 'सेटिंग्स',
      'history': 'इतिहास',
      'notConnected': 'कनेक्ट नहीं',
      'assistance': 'सहायता',
      'cameraStarting': 'कैमरा शुरू हो रहा है…',
      'cameraUnavailable': 'कैमरा उपलब्ध नहीं',
      'inferencePending': 'इस बिल्ड में सुरक्षित डिटेक्शन अभी सक्रिय नहीं है।',
      'mode': 'मोड',
      'edgeServer': 'एज सर्वर',
      'onDevice': 'डिवाइस पर',
      'speed': 'गति',
      'normal': 'सामान्य',
      'pause': 'रोकें',
      'resume': 'जारी रखें',
      'stop': 'बंद',
      'torch': 'टॉर्च',
      'general': 'सामान्य',
      'detection': 'डिटेक्शन',
      'audio': 'ऑडियो',
      'about': 'परिचय',
      'serverConnection': 'सर्वर कनेक्शन',
      'serverIp': 'सर्वर IP',
      'port': 'पोर्ट',
      'feedback': 'ऑडियो और फीडबैक',
      'language': 'भाषा',
      'speechRate': 'बोलने की गति',
      'vibration': 'वाइब्रेशन',
      'hapticIntensity': 'हैप्टिक तीव्रता',
      'medium': 'मध्यम',
      'saveChanges': 'परिवर्तन सहेजें',
      'languageTitle': 'भाषा',
      'languageHint': 'यह ऐप इंटरफ़ेस और वॉइस-गाइडेंस की भाषा बदलता है।',
      'connection': 'कनेक्शन',
      'endpointConfigured': 'एंडपॉइंट कॉन्फ़िगर है',
      'transportPending': 'Secure UDP Protocol v2 मोबाइल ट्रांसपोर्ट अभी कनेक्ट नहीं है।',
      'connectionHealth': 'कनेक्शन स्थिति',
      'packetsSent': 'पैकेट भेजे',
      'packetsReceived': 'पैकेट मिले',
      'packetLoss': 'पैकेट लॉस',
      'lastUpdate': 'अंतिम अपडेट',
      'reconnection': 'रीकनेक्शन',
      'autoReconnect': 'ऑटो रीकनेक्ट',
      'reconnectInterval': 'रीकनेक्ट अंतराल',
      'seconds5': '5 सेकंड',
      'testConnection': 'कनेक्शन टेस्ट',
      'endpointValid': 'एंडपॉइंट फ़ॉर्मेट सही है। सुरक्षित ट्रांसपोर्ट अभी बाकी है।',
      'detectionSettings': 'डिटेक्शन सेटिंग्स',
      'confidenceThreshold': 'कॉन्फिडेंस थ्रेशोल्ड',
      'detectClasses': 'डिटेक्ट क्लास',
      'person': 'व्यक्ति',
      'vehicle': 'वाहन',
      'bicycle': 'साइकिल',
      'motorcycle': 'मोटरसाइकिल',
      'obstacle': 'बाधा',
      'stairs': 'सीढ़ियाँ',
      'curb': 'कर्ब',
      'historyEmpty': 'अभी कोई डिटेक्शन इतिहास रिकॉर्ड नहीं हुआ है।',
      'historyHint': 'डिटेक्शन पाइपलाइन जुड़ने के बाद इवेंट यहाँ दिखेंगे।',
      'today': 'आज',
      'privacyPolicy': 'गोपनीयता नीति',
      'openSourceLicenses': 'ओपन सोर्स लाइसेंस',
      'howItWorks': 'यह कैसे काम करता है',
      'contact': 'संपर्क',
      'version': 'v1.0.0 मोबाइल डेमो',
      'madeForAccessibility': 'एक्सेसिबिलिटी के लिए बनाया गया',
      'prototypeNotice': 'सहायक प्रोटोटाइप — प्रमाणित नेविगेशन या सुरक्षा उपकरण नहीं।',
      'flashUnavailable': 'इस कैमरे पर टॉर्च उपलब्ध नहीं है।',
      'restartCamera': 'कैमरा फिर शुरू करें',
      'voiceGuidance': 'वॉइस गाइडेंस',
    },
  };

  String get(String key) {
    final selected = _values[languageCode] ?? _values['en-US']!;
    return selected[key] ?? _values['en-US']![key] ?? key;
  }
}
