import '../vision/detection.dart';

class StandaloneStrings {
  const StandaloneStrings(this.languageCode);

  final String languageCode;

  static const _values = <String, Map<String, String>>{
    'en-US': {
      'welcome': 'Welcome to WVAB',
      'welcomeBody': 'All vision processing can run on this Android device. No cloud or external backend is required.',
      'chooseLanguage': 'Choose your language',
      'chooseCamera': 'Choose camera source',
      'phoneCamera': 'Phone camera',
      'phoneCameraBody': 'Use this phone camera for fully offline assistance.',
      'esp32Camera': 'ESP32-CAM',
      'esp32CameraBody': 'Receive encrypted camera frames over local Wi-Fi.',
      'continue': 'Continue',
      'finishSetup': 'Finish setup',
      'cameraSource': 'Camera Source',
      'localRuntime': 'On-device AI',
      'runtimeReady': 'Local detector ready',
      'runtimeStarting': 'Loading local detector…',
      'runtimeUnavailable': 'Local detector unavailable',
      'esp32Pairing': 'ESP32 Pairing',
      'esp32Port': 'ESP32 listen port',
      'aesKey': 'AES key (hex)',
      'authToken': 'Authentication token',
      'savePairing': 'Save secure pairing',
      'pairingRequired': 'Pair the ESP32-CAM before using this source.',
      'immediate': 'immediately ahead',
      'close': 'close ahead',
      'medium': 'ahead',
      'far': 'farther ahead',
      'person': 'Person', 'car': 'Car', 'truck': 'Truck', 'bus': 'Bus',
      'bicycle': 'Bicycle', 'motorcycle': 'Motorcycle', 'traffic light': 'Traffic light',
      'stop sign': 'Stop sign', 'chair': 'Chair', 'bench': 'Bench', 'potted plant': 'Plant',
    },
    'bn-BD': {
      'welcome': 'WVAB-এ স্বাগতম',
      'welcomeBody': 'সব ভিশন প্রসেসিং এই Android ফোনেই চলতে পারে। কোনো ক্লাউড বা আলাদা ব্যাকএন্ড দরকার নেই।',
      'chooseLanguage': 'ভাষা নির্বাচন করুন',
      'chooseCamera': 'ক্যামেরা সোর্স নির্বাচন করুন',
      'phoneCamera': 'ফোন ক্যামেরা',
      'phoneCameraBody': 'সম্পূর্ণ অফলাইনে সহায়তার জন্য এই ফোনের ক্যামেরা ব্যবহার করুন।',
      'esp32Camera': 'ESP32-CAM',
      'esp32CameraBody': 'লোকাল Wi-Fi দিয়ে এনক্রিপ্টেড ক্যামেরা ফ্রেম গ্রহণ করুন।',
      'continue': 'পরবর্তী',
      'finishSetup': 'সেটআপ শেষ করুন',
      'cameraSource': 'ক্যামেরা সোর্স',
      'localRuntime': 'ডিভাইস AI',
      'runtimeReady': 'লোকাল ডিটেক্টর প্রস্তুত',
      'runtimeStarting': 'লোকাল ডিটেক্টর লোড হচ্ছে…',
      'runtimeUnavailable': 'লোকাল ডিটেক্টর পাওয়া যায়নি',
      'esp32Pairing': 'ESP32 পেয়ারিং',
      'esp32Port': 'ESP32 লিসেন পোর্ট',
      'aesKey': 'AES কী (hex)',
      'authToken': 'অথেন্টিকেশন টোকেন',
      'savePairing': 'নিরাপদ পেয়ারিং সংরক্ষণ',
      'pairingRequired': 'এই সোর্স ব্যবহারের আগে ESP32-CAM পেয়ার করুন।',
      'immediate': 'একদম সামনে',
      'close': 'খুব কাছে সামনে',
      'medium': 'সামনে',
      'far': 'আরও দূরে সামনে',
      'person': 'মানুষ', 'car': 'গাড়ি', 'truck': 'ট্রাক', 'bus': 'বাস',
      'bicycle': 'সাইকেল', 'motorcycle': 'মোটরসাইকেল', 'traffic light': 'ট্রাফিক লাইট',
      'stop sign': 'স্টপ সাইন', 'chair': 'চেয়ার', 'bench': 'বেঞ্চ', 'potted plant': 'গাছ',
    },
    'ru-RU': {
      'welcome': 'Добро пожаловать в WVAB',
      'welcomeBody': 'Обработка зрения может выполняться прямо на Android-устройстве. Облако и внешний сервер не требуются.',
      'chooseLanguage': 'Выберите язык',
      'chooseCamera': 'Выберите источник камеры',
      'phoneCamera': 'Камера телефона',
      'phoneCameraBody': 'Использовать камеру телефона полностью офлайн.',
      'esp32Camera': 'ESP32-CAM',
      'esp32CameraBody': 'Получать зашифрованные кадры по локальной Wi-Fi сети.',
      'continue': 'Продолжить',
      'finishSetup': 'Завершить настройку',
      'cameraSource': 'Источник камеры',
      'localRuntime': 'ИИ на устройстве',
      'runtimeReady': 'Локальный детектор готов',
      'runtimeStarting': 'Загрузка локального детектора…',
      'runtimeUnavailable': 'Локальный детектор недоступен',
      'esp32Pairing': 'Сопряжение ESP32',
      'esp32Port': 'UDP-порт ESP32',
      'aesKey': 'Ключ AES (hex)',
      'authToken': 'Токен аутентификации',
      'savePairing': 'Сохранить защищённое сопряжение',
      'pairingRequired': 'Сначала выполните сопряжение с ESP32-CAM.',
      'immediate': 'прямо перед вами',
      'close': 'близко впереди',
      'medium': 'впереди',
      'far': 'дальше впереди',
      'person': 'Человек', 'car': 'Автомобиль', 'truck': 'Грузовик', 'bus': 'Автобус',
      'bicycle': 'Велосипед', 'motorcycle': 'Мотоцикл', 'traffic light': 'Светофор',
      'stop sign': 'Знак стоп', 'chair': 'Стул', 'bench': 'Скамейка', 'potted plant': 'Растение',
    },
    'hi-IN': {
      'welcome': 'WVAB में आपका स्वागत है',
      'welcomeBody': 'सारी विज़न प्रोसेसिंग इसी Android डिवाइस पर चल सकती है। क्लाउड या बाहरी बैकएंड की जरूरत नहीं है।',
      'chooseLanguage': 'अपनी भाषा चुनें',
      'chooseCamera': 'कैमरा स्रोत चुनें',
      'phoneCamera': 'फोन कैमरा',
      'phoneCameraBody': 'पूरी तरह ऑफलाइन सहायता के लिए फोन का कैमरा उपयोग करें।',
      'esp32Camera': 'ESP32-CAM',
      'esp32CameraBody': 'लोकल Wi-Fi पर एन्क्रिप्टेड कैमरा फ्रेम प्राप्त करें।',
      'continue': 'आगे बढ़ें',
      'finishSetup': 'सेटअप पूरा करें',
      'cameraSource': 'कैमरा स्रोत',
      'localRuntime': 'ऑन-डिवाइस AI',
      'runtimeReady': 'लोकल डिटेक्टर तैयार',
      'runtimeStarting': 'लोकल डिटेक्टर लोड हो रहा है…',
      'runtimeUnavailable': 'लोकल डिटेक्टर उपलब्ध नहीं',
      'esp32Pairing': 'ESP32 पेयरिंग',
      'esp32Port': 'ESP32 लिसन पोर्ट',
      'aesKey': 'AES कुंजी (hex)',
      'authToken': 'ऑथेंटिकेशन टोकन',
      'savePairing': 'सुरक्षित पेयरिंग सेव करें',
      'pairingRequired': 'इस स्रोत को उपयोग करने से पहले ESP32-CAM पेयर करें।',
      'immediate': 'बिल्कुल सामने',
      'close': 'बहुत पास सामने',
      'medium': 'सामने',
      'far': 'दूर सामने',
      'person': 'व्यक्ति', 'car': 'कार', 'truck': 'ट्रक', 'bus': 'बस',
      'bicycle': 'साइकिल', 'motorcycle': 'मोटरसाइकिल', 'traffic light': 'ट्रैफिक लाइट',
      'stop sign': 'स्टॉप साइन', 'chair': 'कुर्सी', 'bench': 'बेंच', 'potted plant': 'पौधा',
    },
  };

  String get(String key) => (_values[languageCode] ?? _values['en-US']!)[key] ?? _values['en-US']![key] ?? key;

  String guidanceMessage(String objectLabel, ProximityBand proximity) {
    final object = get(objectLabel);
    final position = get(proximity.name);
    return switch (languageCode) {
      'bn-BD' => '$object $position',
      'ru-RU' => '$object $position',
      'hi-IN' => '$object $position',
      _ => '$object $position',
    };
  }
}
