# ------------------------------------------------------------------ 
# | Name: Md. Shahanur Islam Shagor                                      | 
# | Autonomous Systems & UAV Researcher | Cybersecurity    | Specialist | Software Engineer                                                   |
# | Voronezh State University of Forestry and Technologies     | 
# | Build for Blind people within 15$                                         | 
# _______________________________________________________________| 
